# Robot.
map_frame_id: world
robot_base_frame_id: robot
robot_pose_with_covariance_topic: /vilo/estimate_pose
input_sources:
  front: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /camera_forward/depth/color/points
    queue_size: 1
    publish_on_update: true
    sensor_processor:
      type: structured_light
      cutoff_min_depth: 0.2
      cutoff_max_depth: 1.5
      normal_factor_a: 0.000611
      normal_factor_b: 0.003587
      normal_factor_c: 0.3515
      normal_factor_d: 0
      normal_factor_e: 1
      lateral_factor: 0.01576
      ignore_points_below: -0.5

track_point_frame_id: robot
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
time_tolerance: 0.05
scanning_duration: 0.1
enable_visibility_cleanup: false

visibility_cleanup_rate: 5
min_update_rate: 20
fused_map_publishing_rate: 20
relocate_rate: 20

# Map.
length_in_x: 5.0
length_in_y: 5.0
position_x: 0.0
position_y: 0.0
resolution: 0.03
min_variance: 0.0001
max_variance: 0.05
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.001
surface_normal_positive_axis: z
initialize_elevation_map: true
length_in_x_init_submap: 3.0
length_in_y_init_submap: 3.0
init_submap_variance: 1e-3
target_frame_init_submap: world
